# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ef214cab98ca8ae9461e00a75fc61e73b92a2c3e07fb064ed71a1a9ec2b81a2f5de19239daf925ff28b7eb6574737b4deb19e013cf8295f681106a78feda6f8

test:
  secret_key_base: ba6033b1d5f90c1644ecaf740f0f770319df8ac5d52a404cf8fd17ecc0588e1798e95b1549271826897fcc7b28838ba98aa5122b11eca49ddd05074037fb6d84

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
